### ISSUE TITLE
是否支持gif动图？

### ISSUE THREAD

**Issue by luboq** [kingname/MarkdownPicPicker#10]
看readme说明，好像只支持png？支持gif动图吗？

当然gif动图，不像图片，在剪贴板的格式比较特殊，要特殊处理

但就像从Chrome右键复制gif动图，ctrl-v粘贴到QQ窗口，依然能动一样，说明经过特殊处理，能够以剪贴板为管道，传送过去。

那借鉴其方法，应该也能上传到图床吧？

**Comment by kingname** [comment]
如果你都电脑数macOS的话，你可以直接复制本地的gif的地址到剪贴板，然后运行。它可以把gif上次到图床中。

如果数Windows的话，暂时支持png

**Comment by luboq** [comment]
@kingname 谢谢，早知道有这个工具，就不自己改了

我根据 [这个项目](https://github.com/mjnhmd/markdown-upload-qiniu) 改的工具，也是从剪贴板一键上传七牛，唯一缺陷就是gif动图，要先存成文件，再按另一个快捷键，一键上传

希望继续优化，看能不能windows上支持gif动图啊 <img alt="ghe-emoji" title=":_onion_head_angel:" src="https://cloud.githubusercontent.com/assets/136959/13371074/26e5cfea-dce3-11e5-945b-fe714b8af03d.gif">

**Comment by kingname** [comment]
感谢支持，还请把它介绍给其他人。
