### ISSUE TITLE
只用exe如何配置？

### ISSUE THREAD

**Issue by cqzhao** [kingname/MarkdownPicPicker#11]
我将config.ini放到和exe相同的目录下，运行时还是提示没有找到config.ini，使用默认的图床。请问如何解决

**Comment by kingname** [comment]
创建一个config文件夹，config.ini放在这个文件夹里面。
这个文件夹和exe放在一起

**Comment by kingname** [comment]
http://markdownpicpicker.readthedocs.io/en/latest/#config

这是使用说明。

**Comment by cqzhao** [comment]
哦。好的。可以了。谢谢。
