### ISSUE TITLE
sm.ms不能用了？

### ISSUE THREAD

**Issue by luboq** [kingname/MarkdownPicPicker#15]
七牛云我明白正常，只是请教下sm.ms
是只有我、还是大家都故障了？

![img](https://i.loli.net/2018/02/09/5a7d483fe8fca.png)

**Comment by kingname** [comment]
我这里可以正常访问sm.ms.

![image](https://user-images.githubusercontent.com/5440523/36015946-b1fb4b14-0dab-11e8-93c0-b7a8d9d96d09.png)

你电脑浏览器访问看看

**Comment by luboq** [comment]
抱歉，是我本地的代理问题，谢谢
