### ISSUE TITLE
其实也不用使用AutoHotKey，建个快捷方式在快捷方式里定义快捷键就好了。

### ISSUE THREAD

**Issue by 4rnold** [kingname/MarkdownPicPicker#2]
![](http://o8n1hrt12.bkt.clouddn.com/2016-07-21-15-28-59.png)

**Comment by kingname** [comment]
是的，用这种方式确实可以创建快捷键，我在v0.1的时候也是写了这种方法的。但是我后来移除了这个方法是基于以下3点原因：
1.这种方式添加的快捷键，按下以后有1秒的延迟，不如AutoHotKey快。
2.这种方式添加的快捷键，限定了必需使用Ctrl + Alt这两个键，不如AutoHotKey自由。
3.AutoHotKey这种神器，可以做很多事情，推荐给大家使用。
