### ISSUE TITLE
我自行增加了Chevereto图床的支持，想打包成exe，请问你是用哪个工具？

### ISSUE THREAD

**Issue by cqzhao** [kingname/MarkdownPicPicker#20]
我自行增加了Chevereto图床的支持，想打包成exe，请问你是用哪个工具？

**Comment by kingname** [comment]
希望你能把Chevereto相关的代码通过PR添加到MarkdownPicPicker中来，一起让这个工具更好用。

使用pyinstaller

**Comment by cqzhao** [comment]
好的。我先测试一下。

**Comment by cqzhao** [comment]
@kingname 请问如何打包才能减小exe体积，现在200M+，有点夸张

**Comment by kingname** [comment]
不清楚是什么原因，我打包出来没有这么大。我怀疑你是不是直接用的系统环境的Python？改成虚拟环境的Python，就会小了。

**Comment by cqzhao** [comment]
嗯，确实是在系统环境下弄的。刚试了一下虚拟环境，还是很大。求分享你的install脚本

**Comment by kingname** [comment]
用pyinstaller几乎不需要什么脚本，就一条命令。。。

```
pyinstaller -F markdownpicpicker.py
```

你需要确定你的pyinstaller是安装在虚拟环境中的，而不是使用的系统环境中。

你注意我使用了pipenv来管理虚拟环境，所以你可以通过如下命令来创建一个全新的，安全的虚拟环境：

```
pipenv install
pipenv install pyinstaller
pipenv shell
pyinstaller -F markdownpicpicker.py
```
