### ISSUE TITLE
完善 windows 下的配置文档，按照文档的配置目前提示 There is no picture in clipboard

### ISSUE THREAD

**Issue by ghost** [kingname/MarkdownPicPicker#6]
```
[basic]
picture_folder = pic # the local folder to save image
picture_suffix = png #the format of your image, 'png'.

picture_host = QiniuUploader 

[QiniuUploader]
access_key = Q6sS422O05AasdfasfafgfCcCpF36tqvyQ75Zvzw
secret_key = 6QtAqqTxoSadffadfgewehxPLX2CCmoOaB2aLObM
container_name = picturebed
url = http://7sbpmp.com1.z0.glb.clouddn.com/{}
```

`picture_folder` 指的是什么？是图片上传到七牛后还会在本地的 picture_folder 目录下保存一份副本么？是可选的还是必填的？

`picture_suffix` 指的是上传图片后的格式还是上传图片前我图片本身的后缀？是可选的还是必填的？如果不指定是否有默认行为？

`url` 这个是七牛统一的么？单纯复制文档中的 url 就可以么？

`config` 文件夹是放在和 `MarkdownPicPicker.exe` 同一目录下么?

另外我按照文档的说明配置好后，测试运行程序提示：There is no picture in clipboard. 已经复制了图片的（Ctrl+c 或者右键，复制都不行）

**Comment by kingname** [comment]
抱歉，我的文档没有写清楚。以下是你的问题的答案：

> picture_folder 指的是什么？
> 这个文件夹是你本地保存图片的文件夹名字。你可以随意取名字。必填。
> 
> picture_suffix
> 这是程序生成的图片的后缀名。
> 
> url 这个是七牛统一的么？
> 每个账号的url都不一样，你需要去你的账号里面看。
> 
> config 文件夹是放在和 MarkdownPicPicker.exe 同一目录下么?
> 是的。

另外，目前程序只支持从剪贴板中读取截图，不能直接读取图片文件。你可以使用键盘上面的截屏键`Print Screen`或者QQ 的截图功能截图到剪贴板中，然后再运行这个程序。那个后缀名就是读取了剪贴板里面的截图以后，生成的文件的后缀名。

**Comment by ghost** [comment]
谢谢！那还是有一点不方便。有没有办法直接读取目录下的文件？比如直接拖曳图片到程序中（可能需要GUI），后台自动上传图片到云端并返回图片的外链。

**Comment by kingname** [comment]
因为这个程序在设计的时候，就是希望能使用快捷键来运行它。
你可以看一下这个gif，在里面为了演示截图的过程，我使用了Windows自带的截图工具：![](http://7sbpmp.com1.z0.glb.clouddn.com/MarkdownPicPicker2.gif)

所以它的应用场景是这样的：

你使用截图工具的快捷键，例如QQ的截屏快捷键 Ctrl + Alt + A，然后鼠标选择截图的区域并将截图信息保存到剪贴板中，然后按下键盘上面设定的快捷键（例如Win + C），最后在你的Markdown上面按Ctrl + V 粘贴格式化好以后的链接。整个过程可以在3秒钟内完成。

我想尽量减少鼠标的参与，所以没有打算做拖拽的功能。

不过直接读取本地图片文件的功能，我在下一个版本会加入。

**Comment by ghost** [comment]
嗯，谢谢。测试了下，没有问题。也许可以考虑下根据我 issue 的内容完善一下文档相关说明。

**Comment by kingname** [comment]
OK，非常感谢你的建议。
