### ISSUE TITLE
get picture from clipboard error because: "PNG #THE FORMAT OF YOUR IMAGE, 'PNG'."

### ISSUE THREAD

**Issue by vsxen** [kingname/MarkdownPicPicker#7]
看了 #6 使用QQ或者printscreen 都会显示这个

**Comment by kingname** [comment]
这是因为你的QQ截图的格式是jpg或者bmp。
这个问题很好解决：
1. 使用QQ截一张图，选择保存，在保存格式位置选择png.
2.步骤1只需要做一次。之后新的截图就可以被正常识别了。

**Comment by vsxen** [comment]
![qq 20160927091648](https://cloud.githubusercontent.com/assets/8838032/18857040/2b9a9bf8-8493-11e6-9827-1d0ea72d3b7d.png)
实测无效  printscreen键也是错误

配置
[basic]
picture_folder = pic # the local folder to save image
picture_suffix = png #the format of your image, 'png'.

picture_host = QiniuUploader 

[QiniuUploader]
access_key = WiNiJ***********_ap7-ujBu2Jt0zuX
secret_key = FjU9_xPK**_**********_aK1bYr3r9gmX4UrFEtKu
container_name = blog
url = http://odi**_********.bkt.clouddn.com/{}

是不是大写的问题？

**Comment by kingname** [comment]
那你这个Bug就比较诡异了。我今晚去看一下。

**Comment by kingname** [comment]
你不要用配置文件，先直接用我提供的exe来测试一下。编译好的exe它自带图床。

**Comment by kingname** [comment]
https://github.com/kingname/MarkdownPicPicker/releases/download/v1.0.0/MarkdownPicPicker_v1.0.0.zip

**Comment by kingname** [comment]
你使用自带的图床的时候，问题解决了吗？

**Comment by vsxen** [comment]
前两天 用win7下载了打包好的exe，缺了一个dll文件，现在我测试一下win10

**Comment by vsxen** [comment]
自带的可以上传  （是sm.ms 的图床）
![](http://ooo.0o0.ooo/2016/09/29/57ed1a839293a.png) 

此exe应该需要vs2015 redistributable

**Comment by kingname** [comment]
自带的可以上传，那么就证明程序本身从剪贴板读数据并生成png的功能应该没有问题，应该是你的配置文件哪里没有写对。

**Comment by vsxen** [comment]
![](http://odiu0bweg.bkt.clouddn.com/2016-09-29-22-05-03.png)

**Comment by vsxen** [comment]
![](http://ooo.0o0.ooo/2016/09/29/57ed2057e0513.png) 
那个多余的 "."  出问题了

**Comment by vsxen** [comment]
非常感谢 工具很好用

**Comment by kingname** [comment]
谢谢你的赞赏。也希望你能多提一些PR，让它更好用。
