### ISSUE TITLE
打开exe 配置好config 在stackedit 粘贴成功第一次后就闪退

### ISSUE THREAD

**Issue by hym1884603** [kingname/MarkdownPicPicker#8]
如题
![image](https://cloud.githubusercontent.com/assets/16299739/21771586/e960f854-d6c2-11e6-9653-2824104eafcd.png)
这是 成功的 但是第二次就不行了

**Comment by kingname** [comment]
我看到你提到了**配置好config**, 但是，实际上如果你使用ooo.0o0.ooo这个图床，你是不需要任何配置的。直接运行这个exe就可以了。

那个黑色的框一闪而过不叫闪退，是正常的。图上传完成以后，这个窗口自动就会关闭。

**Comment by hym1884603** [comment]
那你的设计本意就是 每次截图后 就需要执行一次这个exe是吗

**Comment by kingname** [comment]
是这样的。我建议你使用AutoHotKey设置快捷键来启动它。QQ截图->按快捷键->等待黑色窗口消失->粘贴。整个过程只需要3秒钟。

**Comment by hym1884603** [comment]
好的 十分感谢

**Comment by kingname** [comment]
谢谢你使用MarkdownPicPicker，如果你觉得好用的话，还请多多推荐给身边的朋友。也希望你能加入到开发中，开发更多的uploader, 并多提PR。感谢。
